group_name:
  name: group_name
  in: path
  required: true
  description: The name of the group.
  schema:
    type: string

username:
  name: username
  in: path
  required: true
  description: The nickname of the user.
  schema:
    type: string

session:
  in: cookie
  name: SESSION
  schema:
    type: string

interest_id:
  in: path
  required: true
  name: interest_id
  schema:
    type: integer
    format: int64

contact_id:
  in: path
  required: true
  name: contact_id
  schema:
    type: integer
    format: int64
