username:
  name: username
  in: path
  required: true
  description: The nickname of the user.
  schema:
    type: string

session:
  in: cookie
  name: SESSION
  schema:
    type: string

interest_id:
  in: path
  required: true
  name: interest_id
  schema:
    type: integer
    format: int64

contact_id:
  in: path
  required: true
  name: contact_id
  schema:
    type: integer
    format: int64

group_id:
  name: group_id
  in: path
  required: true
  description: The group id.
  schema:
    type: integer
    format: int64

post_id:
  name: post_id
  in: path
  required: true
  description: The post id.
  schema:
    type: integer
    format: int64

comment_id:
  name: comment_id
  in: path
  required: true
  description: The comment id.
  schema:
    type: integer
    format: int64

image_id:
  name: image_id
  in: path
  required: true
  description: The image id.
  schema:
    type: string

Content-Length:
  name: Content-Length
  description: Size of file
  in: header
  schema:
    type: integer
    format: int64

Type:
  name: type
  in: query
  required: true
  schema:
    type: string
    enum: ["profile", "group"]

Include:
  name: include
  in: query
  schema:
    type: array
    items:
      type: integer
      format: int64
Exclude:
  name: exclude
  in: query
  schema:
    type: array
    items:
      type: integer
      format: int64
