[app]
addr = "localhost:6969"
graceful_period = "10s"
request_timeout = "5s"

[db]
addr = "postgres://user:password@localhost:5432/likemind"

[auth]
session_key = "test_key_not_prod"
cookie_max_age = 604800
use_http_only = false
