services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: likemind
      # PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5430:5432"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    command: >
      postgres -c max_connections=1000
               -c shared_buffers=256MB
               -c effective_cache_size=768MB
               -c maintenance_work_mem=64MB
               -c checkpoint_completion_target=0.7
               -c wal_buffers=16MB
               -c default_statistics_target=100
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d likemind" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true
  # localstack:
  #   container_name: localstack
  #   image: localstack/localstack:s3-latest
  #   ports:
  #     - "127.0.0.1:4566:4566"
  #   environment:
  #     - DEBUG=${DEBUG:-0}
  #   volumes:
  #     - s3data:/var/lib/localstack

volumes:
  pgdata:
    driver: local
  s3data:
    driver: local
