// Code generated by ogen, DO NOT EDIT.

package desc

import (
	"io"
)

// HTML page content.
// Ref: #/HTMLPage
type HTMLResponse struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s HTMLResponse) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*HTMLResponse) v1PageGroupGroupNameGetRes()  {}
func (*HTMLResponse) v1PageProfileUsernameGetRes() {}
func (*HTMLResponse) v1PageSearchGetRes()          {}
func (*HTMLResponse) v1PageSigninGetRes()          {}
func (*HTMLResponse) v1PageSignupGetRes()          {}

// A plain text error message.
// Ref: #/ErrorResponse
type InternalError struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s InternalError) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*InternalError) v1PageGroupGroupNameGetRes()  {}
func (*InternalError) v1PageProfileUsernameGetRes() {}
func (*InternalError) v1PageSearchGetRes()          {}
func (*InternalError) v1PageSigninGetRes()          {}
func (*InternalError) v1PageSignupGetRes()          {}

// A plain text error message.
// Ref: #/ErrorResponse
type NotAuthorized struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s NotAuthorized) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*NotAuthorized) v1PageGroupGroupNameGetRes()  {}
func (*NotAuthorized) v1PageProfileUsernameGetRes() {}

// A plain text error message.
// Ref: #/ErrorResponse
type NotFound struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s NotFound) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*NotFound) v1PageGroupGroupNameGetRes()  {}
func (*NotFound) v1PageProfileUsernameGetRes() {}
