// Code generated by ogen, DO NOT EDIT.
package desc

type V1APILogoutPostRes interface {
	v1APILogoutPostRes()
}

type V1APISigninPostRes interface {
	v1APISigninPostRes()
}

type V1APISignupPostRes interface {
	v1APISignupPostRes()
}

type V1PageGroupGroupNameGetRes interface {
	v1PageGroupGroupNameGetRes()
}

type V1PageProfileUsernameGetRes interface {
	v1PageProfileUsernameGetRes()
}

type V1PageSearchGetRes interface {
	v1PageSearchGetRes()
}

type V1PageSigninGetRes interface {
	v1PageSigninGetRes()
}

type V1PageSignupGetRes interface {
	v1PageSignupGetRes()
}
