// Code generated by ogen, DO NOT EDIT.
package desc

type GroupGroupNameGetRes interface {
	groupGroupNameGetRes()
}

type ProfileUsernameGetRes interface {
	profileUsernameGetRes()
}

type SearchGetRes interface {
	searchGetRes()
}

type SigninGetRes interface {
	signinGetRes()
}

type SignupGetRes interface {
	signupGetRes()
}
