// Code generated by ogen, DO NOT EDIT.

package desc

// OperationName is the ogen operation name
type OperationName = string

const (
	V1APILogoutPostOperation          OperationName = "V1APILogoutPost"
	V1APISigninPostOperation          OperationName = "V1APISigninPost"
	V1APISignupPostOperation          OperationName = "V1APISignupPost"
	V1PageGroupGroupNameGetOperation  OperationName = "V1PageGroupGroupNameGet"
	V1PageProfileUsernameGetOperation OperationName = "V1PageProfileUsernameGet"
	V1PageSearchGetOperation          OperationName = "V1PageSearchGet"
	V1PageSigninGetOperation          OperationName = "V1PageSigninGet"
	V1PageSignupGetOperation          OperationName = "V1PageSignupGet"
)
