// Code generated by ogen, DO NOT EDIT.

package desc

import (
	"io"
)

// HTML page content.
// Ref: #/HTMLPage
type HTMLResponse struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s HTMLResponse) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*HTMLResponse) groupGroupNameGetRes()  {}
func (*HTMLResponse) profileUsernameGetRes() {}
func (*HTMLResponse) searchGetRes()          {}
func (*HTMLResponse) signinGetRes()          {}
func (*HTMLResponse) signupGetRes()          {}

// A plain text error message.
// Ref: #/ErrorResponse
type InternalError struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s InternalError) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*InternalError) groupGroupNameGetRes()  {}
func (*InternalError) profileUsernameGetRes() {}
func (*InternalError) searchGetRes()          {}
func (*InternalError) signinGetRes()          {}
func (*InternalError) signupGetRes()          {}

// A plain text error message.
// Ref: #/ErrorResponse
type NotAuthorized struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s NotAuthorized) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*NotAuthorized) groupGroupNameGetRes()  {}
func (*NotAuthorized) profileUsernameGetRes() {}

// A plain text error message.
// Ref: #/ErrorResponse
type NotFound struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s NotFound) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*NotFound) groupGroupNameGetRes()  {}
func (*NotFound) profileUsernameGetRes() {}
