// Code generated by ogen, DO NOT EDIT.
package desc

type V1APIContactContactIDDeleteRes interface {
	v1APIContactContactIDDeleteRes()
}

type V1APIContactContactIDPutRes interface {
	v1APIContactContactIDPutRes()
}

type V1APIContactPostRes interface {
	v1APIContactPostRes()
}

type V1APIInterestInterestIDDeleteRes interface {
	v1APIInterestInterestIDDeleteRes()
}

type V1APIInterestInterestIDPostRes interface {
	v1APIInterestInterestIDPostRes()
}

type V1APILogoutPostRes interface {
	v1APILogoutPostRes()
}

type V1APIProfileDeleteRes interface {
	v1APIProfileDeleteRes()
}

type V1APIProfilePostRes interface {
	v1APIProfilePostRes()
}

type V1APIProfilePutRes interface {
	v1APIProfilePutRes()
}

type V1APISigninPostRes interface {
	v1APISigninPostRes()
}

type V1PageGroupGroupNameGetRes interface {
	v1PageGroupGroupNameGetRes()
}

type V1PageProfileUsernameGetRes interface {
	v1PageProfileUsernameGetRes()
}

type V1PageSearchGetRes interface {
	v1PageSearchGetRes()
}

type V1PageSigninGetRes interface {
	v1PageSigninGetRes()
}

type V1PageSignupGetRes interface {
	v1PageSignupGetRes()
}
