openapi: 3.1.0
info:
  title: Likemind API
  version: 1.0.0
  description: An application similar to a social network for finding interesting friends based on your interests, see [readme for more](https://github.com/prev0id/likemind/blob/master/README.md)

servers:
  - url: http://localhost:8080
    description: local (development) run

paths:
  /v1/page/signin:
    $ref: "./paths/pages.yaml#/signin"
  /v1/page/signup:
    $ref: "./paths/pages.yaml#/signup"
  /v1/page/profile/{username}:
    $ref: "./paths/pages.yaml#/profile"
  /v1/page/group/{group_id}:
    $ref: "./paths/pages.yaml#/group"
  /v1/page/search:
    $ref: "./paths/pages.yaml#/search"
  /v1/api/signin:
    $ref: "./paths/api.yaml#/signin"
  /v1/api/logout:
    $ref: "./paths/api.yaml#/logout"
  /v1/api/profile:
    $ref: "./paths/api.yaml#/profile"
  /v1/api/profile/image:
    $ref: "./paths/api.yaml#/create_profile_image"
  /v1/api/profile/image/{image_id}:
    $ref: "./paths/api.yaml#/profile_image"
  /v1/api/profile/email:
    $ref: "./paths/api.yaml#/profile_image"
  /v1/api/profile/password:
    $ref: "./paths/api.yaml#/profile_image"
  /v1/api/interest/{interest_id}:
    $ref: "./paths/api.yaml#/interest"
  /v1/api/contact:
    $ref: "./paths/api.yaml#/create_contact"
  /v1/api/contact/{contact_id}:
    $ref: "./paths/api.yaml#/contact"
  /v1/api/group:
    $ref: "./paths/api.yaml#/create_group"
  /v1/api/group/{group_id}:
    $ref: "./paths/api.yaml#/group"
  /v1/api/group/{group_id}/post:
    $ref: "./paths/api.yaml#/create_post"
  /v1/api/group/{group_id}/post/{post_id}:
    $ref: "./paths/api.yaml#/post"
  /v1/api/group/{group_id}/post/{post_id}/comment:
    $ref: "./paths/api.yaml#/create_comment"
  /v1/api/group/{group_id}/post/{post_id}/comment/{comment_id}:
    $ref: "./paths/api.yaml#/comment"

components:
  securitySchemes:
    SessionAuth:
      $ref: "./components/securitySchemas.yaml#/SessionAuth"

tags:
  - name: page
    description: handler returns full html page
    externalDocs:
      url: https://github.com/prev0id/likemind/blob/master/docs/pages.md
  - name: user
    description: user api
    externalDocs:
      url: https://github.com/prev0id/likemind/blob/master/docs/user_api.md
  - name: group
    description: group api
    externalDocs:
      url: https://github.com/prev0id/likemind/blob/master/docs/group_api.md
  - name: search
    description: search api
    externalDocs:
      url: https://github.com/prev0id/likemind/blob/master/docs/search_api.md
